config/routes.rb
Rails.application.routes.draw do
  
  root 'results#form'
  
  post '/generate', to: 'results#generate'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  
  def form
    
  end
  
  def generate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/_header.html.erb
<header class="header">
  <div class="image-container left">
    <%= image_tag 'attribute1', class: 'image' %>
  </div>
  <div class="image-container right">
    <%= image_tag 'attribute1', class: 'image' %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret Santa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/results/form.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag generate_path, method: :post, class: "form" do %>
      <% 5.times do %>
        <div class="form-inline">
          <div class="form-group">
            <%= text_field_tag 'names[]', nil ,class: 'form-control', placeholder: 'Name' %>
          </div>
          <div class="form-group">
            <%= text_field_tag 'emails[]', nil ,class: 'form-control', placeholder: 'E-mail' %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>